version: '3.7'
services:

  postgres:
    image: postgres:9.5-alpine
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo 
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 8080:8080
    links:
      - postgres:db

  odoo8xenial:
    build:
      context: odoo8-xenial
    depends_on:
      - postgres
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - odoo-var:opt/odoo/var:rw
      - odoo-etc:/opt/odoo/etc:rw
      - odoo-adons:/opt/odoo/sources/odoo/addons:rw
      - odoo-session:/opt/odoo/data/session:rw
      - odoo-data:/opt/odoo/data:rw
    restart: unless-stopped
    ports:
      - 8069:80
      - 8072:8072
    links:
      - postgres:db

volumes:
  odoo-var:
  odoo-adons:
  odoo-session:
  odoo-data:
  postgres-data:
