version: '3.7'
services:

  postgres:
    image: xcgd/postgresql:9.5
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./persistence/postgresql/var/log/postgresql:/var/log/postgresql:rw
      - ./persistence/postgresql/var/lib/postgresql:/var/lib/postgresql:rw
      - ./persistence/postgresql/etc/postgresql:/etc/postgresql:rw

  odoo8xenial:
    build:
      context: odoo8-xenial
    depends_on:
      - postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./persistence/odoo8xenial/opt/odoo/var:/opt/odoo/var:rw
      - ./persistence/odoo8xenial/opt/odoo/etc:/opt/odoo/etc:rw
      - ./persistence/odoo8xenial/opt/odoo/sources/odoo/addons:/opt/odoo/sources/odoo/addons:rw
      - ./persistence/odoo8xenial/opt/odoo/data:/opt/odoo/data:rw
      - odoo-session:/opt/odoo/data/session:rw
      - odoo-data:/opt/odoo/data:rw
    restart: unless-stopped
    ports:
      - 8069:8069
      - 8072:8072
    links:
      - postgres:db

volumes:
  odoo-session:
  odoo-data:
                        